server:
  port: 8081
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/JWT_Security
    username: postgres
    password: Okafor.com
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

